name: dirac-development

channels:
  - diracgrid
  - conda-forge
  - defaults

dependencies:
  # Temporary workarounds
  - astroid 2.5.6  # https://github.com/PyCQA/astroid/issues/1006 and https://github.com/PyCQA/astroid/issues/1007
  # runtime
  - python =3.9
  - pip
  - boto3
  - cachetools
  - certifi
  - cmreshandler >1.0.0b4
  - docutils
  - elasticsearch-dsl
  - future
  - gitpython >=2.1.0
  - m2crypto >=0.36,!=0.38.0
  - matplotlib
  - numpy
  - pexpect >=4.0.1
  - pillow
  - prompt-toolkit >=3,<4
  - psutil >=4.2.0
  - pyasn1 >0.4.1
  - pyasn1-modules
  - python-json-logger >=0.1.8
  - pytz >=2015.7
  - recommonmark
  - requests >=2.9.1
  - six >=1.10
  - sqlalchemy >=1.0.9
  - stomp.py =4.1.23
  - suds-jurko >=0.6
  - xmltodict
  - pycurl
  - voms
  - python-gfal2
  - mysqlclient
  - diraccfg
  - subprocess32
  - ldap3
  - importlib_resources
  # testing and development
  - autopep8
  - caniusepython3
  - coverage
  - docker-compose
  - hypothesis
  - ipython
  - make
  - mock
  - parameterized
  - pylint >=1.6.5
  - pyparsing >=2.0.6
  - pytest >=3.6
  - pytest-cov >=2.2.0
  - pytest-mock
  - setuptools-scm
  - shellcheck
  - typer
  - typer-cli
  - flaky
  # docs
  - pygments >=1.5
  - sphinx
  - graphviz
  # unused
  - funcsigs
  - jinja2
  # PyPI deployment
  - readme_renderer
  - twine
  - uritemplate
  # - readline >=6.2.4 in the standard library
  - simplejson >=3.8.1
  #- tornado >=5.0.0,<6.0.0
  - typing >=3.6.6
  - pyyaml
  - pip:
    # This is a fork of tornado with a patch to allow for configurable iostream
    # It should eventually be part of DIRACGrid
    - git+https://github.com/DIRACGrid/tornado.git@iostreamConfigurable
    # This is an extension of Tornado to use M2Crypto
    # It should eventually be part of DIRACGrid
    - git+https://github.com/DIRACGrid/tornado_m2crypto
    # fts-rest doesn't support Python 3, this branch changed has just enough to
    # make it importing possible
    - git+https://gitlab.cern.ch/cburr/fts-rest.git@python3
    - rucio-clients >=1.26.0rc1
    - -e .
